### ISSUE TITLE
JS module imports fail in CoffeeScript modules

### ISSUE THREAD

**Issue by eugenet8k** [helixbass/eslint-plugin-coffee#33]
Hi, thank you so much for the great work! We are trying to adopt the new plugin for our big codebase which is a mix of Coffee and JS modules. Moreover, some JS modules are being imported into Coffee modules and vise versa.

We used `overrides` in the `.eslintrc` to add rules and parser for coffee files:

```
{
  "parser": "babel-eslint",
  "extends": [
    "airbnb",
    "prettier",
    "prettier/react",
    "plugin:prettier/recommended",
    "plugin:mocha/recommended"
  ],
  "plugins": ["prettier", "react-hooks", "emotion", "mocha"],
  "overrides": [
    {
      "files": ["**/*.coffee"],
      "parser": "eslint-plugin-coffee",
      "plugins": ["coffee"],
      "extends": [
        "plugin:coffee/airbnb",
        "plugin:coffee/import"
      ]
    }
  ]
}
```

and we have all the recent versions in packages.json:
```
    "eslint": "6.8.0",
    "eslint-config-airbnb": "18.0.1",
    "eslint-config-prettier": "6.9.0",
    "eslint-plugin-coffee": "0.1.12",
    "eslint-plugin-emotion": "10.0.27",
    "eslint-plugin-import": "2.20.0",
    "eslint-plugin-jsx-a11y": "6.2.3",
    "eslint-plugin-mocha": "6.2.2",
    "eslint-plugin-prettier": "3.1.2",
    "eslint-plugin-react": "7.18.0",
    "eslint-plugin-react-hooks": "2.3.0",
```

Our problem is that the JS imports in Coffee files can't be processed. Let's say I have a Coffee module with this line:
```
import {helper} from '../lib/util'  # a JS module
```

The VSCode ESLint error says:
_"Parse errors in imported module '../lib/util': parser.parse is not a function (undefined:undefined)eslint(import/named)"_

and for this line:
```
import MyClass from '../ui/class' # a JS module
```

The VSCode ESLint error says:
_"Parse errors in imported module '../ui/class': parser.parse is not a function (undefined:undefined)eslint(coffee/no-named-as-default-member)"_

If I run via command line for each JS import line I get a message:

```
`parseForESLint` from parser `/app/node_modules/eslint-plugin-coffee/lib/index.js` is invalid and will just be ignored
```

Is it possible to overcome this problem via eslint config? Thank you in advance.

**Comment by helixbass** [comment]
Hi, you're welcome!

Cool I didn't know about `overrides`, I wasn't sure what the options were for using ESLint with a mixed Coffeescript/JS project

Looks like the issue is that `eslint-plugin-import` is trying to insist on using the Coffeescript parser when parsing *all* imported modules in Coffeescript source files

This seems to be because currently `eslint-plugin-coffee`'s [config for `eslint-plugin-import`](https://github.com/helixbass/eslint-plugin-coffee/blob/master/src/index.coffee#L1055) specifies:
```
'import/parsers':
  'eslint-plugin-coffee/lib/parser': ['.coffee']
```

It's possible this default config should be extended to include a separate parser for `.js`/`.jsx` files (the tricky part seems like knowing whether to use eg `babel-eslint` for the JS parser)

But overriding this manually should work for you (see below)

I also found in my testing that in order to correctly check imports of `.coffee` modules from JS files, the default import config for JS files needed to be updated (eg by default `eslint-plugin-import` still ignores `.coffee` files)

So in total can you try adding to your `.eslintrc`:
```
  ...
  "settings": {
    "import/extensions": [".coffee", ".js", ".jsx"],
    "import/parsers": {
      "eslint-plugin-coffee/lib/parser": [".coffee"],
      "babel-eslint": [".js", ".jsx"]
    },
    "import/resolver": {
      "node": {
        "extensions": [".coffee", ".js", ".jsx"]
      }
    },
    "import/ignore": ["node_modules", "\\.(scss|css|less|hbs|svg|json)$"]
  },
  "overrides": [
    {
      ...
      "settings": {
        "import/parsers": {
          "eslint-plugin-coffee/lib/parser": [".coffee"],
          "babel-eslint": [".js", ".jsx"]
        }
    }
  ]
```

In my testing this forced the correct parser to be used by import rules for both JS and Coffeescript source files, here's the [test repo](https://github.com/helixbass/coffee-js-mixed-eslint-example)

**Comment by eugenet8k** [comment]
@helixbass thank you, your suggestion and config example made it work!
