### ISSUE TITLE
Migrate from babel-eslint to @babel/eslint-parser

### ISSUE THREAD

**Issue by n-rodriguez** [helixbass/eslint-plugin-coffee#50]
https://github.com/babel/babel-eslint : 

> babel-eslint is now @babel/eslint-parser and has moved into the Babel monorepo.

**Comment by helixbass** [comment]
Hi, `eslint-plugin-coffee` uses an old version of `babel-eslint` (`^7.2.2`) because after that version the output of an ESLint-compatible AST ("ESTree" format rather than "Babel" format) was handled by the new `estree` Babel parser plugin rather than `babel-eslint` itself. But we need that transformation from Babel AST -> ESTree AST from `babel-eslint`

So since with the current architecture we won't be upgrading to a newer version of `babel-eslint`/`@babel/eslint-parser`, I think it makes sense to leave the dependency as-is
